name: vrum_mobile
description: A new Flutter application for VRUM application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  background_location: ^0.4.1
  rxdart: ^0.26.0
  json_annotation: ^3.1.1
  intl: ^0.17.0
  uuid: ^3.0.4
  font_awesome_flutter: ^9.0.0
  flutter:
    sdk: flutter
  http: ^0.13.1
  fluttertoast: ^8.0.3
  hexcolor: ^2.0.3
  maps_toolkit: ^1.1.0+2
  url_launcher: ^6.0.3
  google_maps_flutter: ^2.0.3
  flutter_tts: ^3.0.0
  shared_preferences: ^2.0.5
  permission_handler:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^1.10.12
  json_serializable: ^3.5.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/pedestrian_app/
    - assets/fitness_app/
    - assets/images/
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# Security Store for deplying to sotre
 # What is your first and last name?
 # [Unknown]:  Debbie English
 # What is the name of your organizational unit?
 # [Unknown]:  VRUM
 # What is the name of your organization?
 # [Unknown]:  VRUM
 # What is the name of your City or Locality?
 # [Unknown]:  Fort Collins
 # What is the name of your State or Province?
 # [Unknown]:  CO
 # What is the two-letter country code for this unit?
 # [Unknown]:  CO
 # Is CN=Debbie English, OU=VRUM, O=VRUM, L=Fort Collins, ST=CO, C=CO correct?
 # [no]:  yes
  #Password:4499VRUM!
  #Alias - key PSW 4499VRUM!
#Location: C:\users\debbie\key_FRUM.jks
  #[Storing VRUM_Keystore.keystore]
  #updated the version number  in the build.gradel update  versionCode 2 to another number